[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nucleopt"
version = "1.0.5"
description = "Optimizers from the nucleobench package."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Move37 Labs", email = "joel.shor@move37labs.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch>=2.2",
    "numpy>=1.16",
    "scipy",
    "pandas",
    "h5py",
    "pyarrow",
    "fastparquet",
    "google-cloud-storage",
    "gcsfs",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-xdist",
    "pytest-repeat",
    "pytest-cov",
    "coverage",
    "pyclean",
]

[project.urls]
"Homepage" = "https://github.com/move37-labs/nucleobench"
"Bug Tracker" = "https://github.com/move37-labs/nucleobench/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["nucleobench", "nucleobench.*"]
exclude = ["nucleobench.models", "nucleobench.models.*"]

[tool.black]
line-length = 88
target-version = ["py310", "py311"]

[tool.isort]
profile = "black"
line_length = 88

[tool.pytest.ini_options]
testpaths = ["nucleobench"]
python_files = "*_test.py"