name: Lint and Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Ruff Lint
        uses: astral-sh/ruff-action@v3
        with:
          args: "check"

      - name: Run Ruff Format
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
