name: Saluki Integration Tests (Micromamba)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          post-cleanup: 'all'

      - name: Run Saluki integration tests
        shell: micromamba-shell {0}
        run: |
          pytest -v -m saluki integration_tests/saluki_integration_test.py
