name: Type Checking

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true
          post-cleanup: 'all'

      - name: Run Mypy
        shell: micromamba-shell {0}
        run: mypy nucleobench/
